Fixes: #1

diff --git a/gh-templates/commit-msg b/gh-templates/commit-msg
--- a/gh-templates/commit-msg
+++ b/gh-templates/commit-msg
@@ -29,8 +29,9 @@ fi
 issuenum=`sed -n 's/^Fixes: *#\([0-9]*\)/\1/p' "$1"`
 if [ -n "$issuenum" ] && [ "$issuenum" -eq "$issuenum" ] 2>/dev/null; then
 	# gh is installed as part of knoxTemplates->install.sh repo
-	gh issue view $issuenum 2>/dev/null | head -2 | grep "^state:.*OPEN" > /dev/null
-	[[ $? -ne 0 ]] && printf "${RED}Could not find an OPEN issue #$issuenum on the repo.${NC}\n" && exit 1
+	# gh issue view $issuenum 2>/dev/null | head -2 | grep "^state:.*OPEN" > /dev/null
+	# [[ $? -ne 0 ]] && printf "${RED}Could not find an OPEN issue #$issuenum on the repo.${NC}\n" && exit 1
+	echo ;
 else
 	printf "${RED}Issue number format [$issuenum] is incorrect.${NC}\n"
 	exit 1
