Fixes: #NUM

diff --git a/gh-templates/commit-msg b/gh-templates/commit-msg
--- a/gh-templates/commit-msg
+++ b/gh-templates/commit-msg
@@ -30,6 +30,5 @@ issuenum=`sed -n 's/^Fixes: *#\([0-9]*\)/\1/p' "$1"`
 if [ -n "$issuenum" ] && [ "$issuenum" -eq "$issuenum" ] 2>/dev/null; then
 	# gh is installed as part of knoxTemplates->install.sh repo
 	gh issue view $issuenum 2>/dev/null | head -2 | grep "^state:.*OPEN" > /dev/null
-	[[ $? -ne 0 ]] && printf "${RED}Could not find an OPEN issue #$issuenum on the repo.${NC}\n"
-	exit 1
+	[[ $? -ne 0 ]] && printf "${RED}Could not find an OPEN issue #$issuenum on the repo.${NC}\n" && exit 1
 fi
